kibot:
  version: 1
globals:
    units: 'millimeters'
    colored_tht_resistors: true # Add color bands to the 3D models of KiCad THT resistors.
    cache_3d_resistors: true # Cache the generated 3D models of colored resistors
    default_resistor_tolerance: 10 # When no tolerance is specified we use +/-10%
    date_time_format: '%Y-%m-%d'
preflight:
    set_text_variables:
      - name: PROJECTNAME
        text: '%f'
    check_zone_fills: true
    erc:
        enabled: true
        dir: 'docs/build_reports'
        dont_stop: true
    drc:
        enabled: true
        dir: 'docs/build_reports'
        all_track_errors: true
        dont_stop: true
    check_fields:
      - field: Value
        regex: '(.|\s)*\S(.|\s)*' # Not Blank
        severity: "warning"
      - field: Datasheet
        regex: '^(?!\s*$|~$).+' # Not Blank or ~
        severity: "warning"
      - field: Footprint
        regex: '(.|\s)*\S(.|\s)*' # Not Blank
        severity: "warning"
      - field: Source
        regex: '(.|\s)*\S(.|\s)*' # Not Blank
        severity: "warning"
    update_pcb_characteristics: true
    draw_fancy_stackup:
        draw_stackup: true
        columns: 
            - drawing
            - layer
            - thickness
            - dielectric
            - layer_type
    update_xml:
        enabled: true
        as_warnings: true
outputs:
  - name: Datasheets
    type: download_datasheets
    dir: '+docs/datasheets'
    options:
        output: '${VALUE}.pdf'
        dnf: true
  - name: SchematicPDFs
    type: pdf_sch_print
    dir: '+docs'
    options:
        color_theme: "KiCAD Default"
        monochrome: true
  - name: Boardview
    type: boardview
    dir: '+gerbers'
  - name: PCB_PDFs
    type: pcb_print
    dir: '+docs'
    options:
        force_edge_cuts: true
        plot_sheet_reference: true
        sheet_reference_layout: @WORKSHEET@
        pages:
          - layers: 'F.Silkscreen'
          - layers: 'F.Courtyard'
          - layers: 'F.Mask'
          - layers: 'F.Paste'
          - layers: 'F.Cu'
          - layers: 'In1.Cu'
          - layers: 'In2.Cu'
          - layers: 'B.Cu'
          - layers: 'B.Paste'
          - layers: 'B.Mask'
          - layers: 'B.Courtyard'
          - layers: 'B.Silkscreen'
          - layers: 'user'
            layer_var: 'Comments'
          - layers: 'all'
            layer_var: 'All'
  - name: Netlist
    type: netlist
    dir: '+gerbers'
    options:
        format: 'classic'
  - name: IBOM
    type: ibom
    dir: '+docs'
    options:
        output: '%f-bom.%x'
        show_fields: 'Value,Footprint,Source,Critical,DNP'
        dark_mode: true
        layer_view: 'F'
        checkboxes: 'Placed,Sourced'
        include_nets: true
        highlight_pin1: true
        dnp_field: 'DNP'
  - name: PCB_Gerber
    type: gerber
    dir: '+gerbers'
    layers: 'all'
    options:
        plot_sheet_reference: true
  - name: Drill_File
    type: excellon
    dir: '+gerbers'
    options:
        minimal_header: true
        zeros_format: 'SUPPRESS_LEADING'
  - name: Position_File
    type: position
    dir: '+gerbers'
  - name: Step_Model
    type: step
    dir: '+3d_models'
  - name: Stencil_3D
    type: stencil_3d
    dir: '+3d_models'
    options:
        thickness: 0.15 # [mm]
        create_preview: true
  - name: PCB_Draw
    type: pcbdraw
    dir: '+docs/images'
    options:
        output: '%f-pcb-%i%I%v.%x'
        format: 'png'
        show_components: 'none'
  - name: STL_Model
    type: blender_export
    dir: '+3d_models'
    options:
        outputs:
            type: stl
  - name: 3D Renders
    type: blender_export
    dir: '+docs/images'
    options:
        point_of_view:
          - view: 'top'
            rotate_x: 20
            rotate_y: 20
          - view: 'bottom'
            rotate_x: 20
            rotate_y: 20
          - view: 'front'
            rotate_x: 0
            rotate_y: 20
          - view: 'left'
            rotate_x: 0
            rotate_y: 20
          - view: 'right'
            rotate_x: 0
            rotate_y: 20
        render_options:
            samples: 10
            transparent_background: true
            auto_crop: true