main:
  - title: "Quick-Start"
    url: /quick-start
  - title: "Documents"
    url: /docs
  - title: "Gallery"
    url: /gallery
  - title: "Files"
    url: /files
  - title: "Other"
    url: "https://matt-santos.github.io/projects"
    target: _blank

#docs:
#  - title:
#    url: 