# _config.yml

# Site Settings
title: "Project Template"
description: "Short Description"
#subtitle: "Version 1.0"
repository: "Matt-Santos/project-template"

# Theme Settings
name: "Matthew Santos"
enable_copy_code_button: true
logo: "/assets/documents/images/logo.png"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"
title_separator: "|"
locale: "en-US"
atom_feed:
  hide: true
footer:
  links:
    - label: "Contact"
      url: "https://matt-santos.github.io/#contact"

# Jekyll Build settings
timezone: America/Toronto
theme: null
markdown: GFM